version: '3'
services:
  orri:
    image: vortical/orri
    ports:
      - 8080:8080
    restart: always      
  spacefield:
    image: vortical/spacefield
    ports:
      - 8000:8000
    volumes:
      - ~/src/data:/spacefield/data
